env:
  global:
    - "FTP_USER=mirfish"
# FTP_PASSWORD
    - secure: >
        DeIBlAe3nPASxxmlYSMYdOrrn3LIHqvgIi4CcZAI1NO8A7n9WnHk+NNv8T17bbnaRxqw7Ebw7vjd8BREVmUSjBBcYxdz58oV9vtGBtEJphquQwmwV/50CWSRvYynmJ/gDXgDgC/+XnJaGO2IhoqP8L4jBxwT80715G8FXoPmqKU=
# API Key
    - "sham_key=xXxAPIKEYxXx"
    - secure: >
        N6pKUOL3YCaJhhfk22jnf4PvjLFBsOhMKK0F5d0SNAFGPb/G5dFo+kBZEVFNfmn8ODMqrlpNzN7bisIaLcEVLKDHWm07QOcwLZqvjEvey9OrbhyuqB35IowaJcNZuRfK6Oif1kGSydz0UD0CJjyt9FlOp/HJKM4AtdPfwUcPN/w=
branches:
  only: master

language: node_js
node_js: 
  - "stable"

before_install:
  - 'npm install -g grunt-cli bower'
  - 'gem install jekyll'
  - 'gem install compass'

install: 
  - 'bower install'
  - 'npm install'

script:
  - 'sed -i -e "s/$sham_key/$API_KEY/g" ./_includes/_form.html'
  - 'grunt build'

after_success:
  - 'cd _site && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://nogorweb.com/{} \;'
  - 'echo Done :D'