# Site settings
title: Mir Fisheries 
url: "http://mirfish.adkave.com/"

logo: 'img/adkave.png'

second-logo:
  img: 'img/logo.png'
  title: 'মির ফিশারিজ'
  text: >
    <i class="fa fa-ফিস"></i> উন্নত যাতের পোনা

slides:
#  - caption: 'Slide 1'
#    thumb: ''
#    img: 'img/responsive.jpeg'

desc:
  type: para
  heading: >
    উন্নত যাতের পোনা কিনতে আমাদের সাথে যোগাযোগ করুন! বেস্ট কোয়ালিটির জিনিশ দেয়া হবে 
  text: >
    ফাইনালে বিজয়ী দলের হাতে বিশ্বকাপের ট্রফি না দিতে দেওয়ায় ২৯ মার্চ আইসিসি সভাপতি আ হ ম মুস্তফা কামাল সাংবাদিকদের জানিয়েছিলেন, 
    ‘দেশে ফিরে সব বলব’। আজ দুপুর একটার দিকে শাহজালাল আন্তর্জাতিক বিমানবন্দরে নেমেই ‘সব বললেন’। 
    ঘোষণা দিলেন সভাপতির পদ থেকে পদত্যাগের। জানালেন, ১৬ কোটি মানুষকে ‘ছোট’ করে এ পদে থাকতে চান না তিনি। 
# type: table
# title: Awesome Item
# price: '1,000,000'
# warn: a very nice warning to spammers
# items:
#   - icon: car
#     text: Dodge Charger

adsense: #ad codes goes here, adsense or otherwise

analytics: UA-61372863-1

footer:
  credits: 'Adkave'
  links:
    - link: '//adkave.com'
      text: 'Adkave'

###############################################################################
# Build settings
markdown: kramdown

permalink: ''
defaults:
  -
    scope:
      path: ''
    values:
      layout: default

exclude:
  - 'node_modules'
  - 'components'
  - 'src'
  - 'config.rb'
  - 'Gruntfile.js'
  - 'package.js'
  - 'bower.json'
  - 'README.md'